# Generated by Django 4.1.5 on 2023-01-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_departments_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='doctors')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.departments')),
            ],
        ),
    ]
